1. 필요 패키지 불러오기

In [ ]:
import tensorflow as tf          # 전문가는 파이토치, H2O, MXnet 등 있음
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.utils import to_categorical

2. 데이터 전처리 연습

In [ ]:
df = pd.read_csv("creditset2.csv")

#데이터를 둘(각각 train, test)로 나눠주는 함수, test size 비율만큼 test에 해당하는 데이터의 크기
train_test_split([1,2,3,4], test_size=0.2)

#함수에 들어간 입력의 개수 X 2 만큼의 결과가 순서대로 나옴, train, test 각각
train_test_split(df, test_size=0.2)

#각각 다른 이름으로 할당시킬 수 있음
train_df, test_df = train_test_split(df, test_size=0.2)


#데이터프레임인 df에서 컬럼 선택: df[ [ 컬럼이름을 여기에  ]    ]
x = df[['income', 'age', 'loan']] #해당 컬럼 3개를 갖는 데이터프레임
y = df[['default10yr']] #해당 컬럼을 갖는 데이터프레임

#One hot encoding
y = to_categorical(df[['default10yr']]) #One hot encoding 시키기

#scaling
x = MinMaxScaler().fit_transform(x) #스케일링 시키기

3. 데이터 읽고 전처리까지 (분류모형의 경우)

In [ ]:
df = pd.read_csv("creditset2.csv")  # 1) 데이터 읽기
x = df[['income', 'age', 'loan']]   # 2) 변수 선택, x
y = to_categorical(df[['default10yr']]) #3) 변수 선택, target 범주형의 원핫인코딩
train_x, test_x, train_y, test_y = train_test_split(x,y, test_size=0.2) #4) 파티셔닝
train_x = MinMaxScaler().fit_transform(train_x) #5)파티셔닝된 것 중 X의 스케일링
test_x = MinMaxScaler().fit_transform(test_x) #5)파티셔닝된 것 중 X의 스케일링

리뷰. MLPClassifier

In [ ]:
from sklearn.neural_network import MLPClassifier         # 간단하게 쓸 수 있음.  단점은 기성품임 흔한 그런거. 쉬운 방법

clf = MLPClassifier(hidden_layer_sizes=(3, 6, 2 ))
clf.fit(train_x, train_y)

print(clf.score(test_x, test_y))

0.935


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
clf.coefs_ # 은닉층에서 각 가중치 값 ??, 가중치의 갯수를 파라미터 갯수로 표현??

[array([[-6.27542586e-01,  4.95146213e-16,  9.15947862e-01],
        [-1.15519568e+00, -1.40592929e-04,  1.50975363e+00],
        [ 1.71091756e+00, -1.39224884e-34, -1.44297015e+00]]),
 array([[ 1.54202991e-05, -1.59740625e-03,  1.34809302e-08,
          1.20781594e+00, -1.65210125e+00,  1.20660407e-27],
        [ 4.44015495e-05, -7.81373707e-07,  4.89067191e-03,
         -1.15157958e-25,  1.19590886e-02, -1.87005439e-07],
        [ 4.30095263e-33, -1.27890595e-02, -4.15719917e-11,
         -7.75949644e-01,  1.41902046e+00, -7.98271508e-03]]),
 array([[ 8.84829773e-03,  7.91062526e-09],
        [-3.65943130e-07, -3.70730916e-24],
        [ 4.07266661e-03, -1.64951619e-22],
        [-6.80692386e-01, -1.34301113e+00],
        [ 1.95849803e+00,  1.17481892e+00],
        [ 1.23328677e-20,  4.54401686e-03]]),
 array([[ 1.45954646,  0.1730428 ],
        [-0.40767042, -1.6000728 ]])]

4. 모델링 및 적합

In [ ]:
#DNN                                       # 안 쉬운 방법
from tensorflow.keras.models import Sequential       # 시퀜샬 객체를 만든다
from tensorflow.keras.layers import Dense

#Hidden layer 구성하기
model = Sequential()
model.add(Dense(3, activation = 'relu', input_shape = (3, ))) #첫번째 은닉층, 3개입력->2개 은닉층 노드, Desnse: 일반적인 은닉층, Fully connected hidden layer
model.add(Dense(6, activation = 'relu')) #두번째 은닉층, 2개입력->6개 은닉층 노드, Desnse: 일반적인 은닉층, Fully connected hidden layer
model.add(Dense(2, activation = 'softmax')) #Desnse: 마지막 은닉층, Fully connected hidden layer, 분류의 경우 softmax

#모형 컴파일
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['acc']) #분류모형은 이대로 사용하기
model.summary()

#모형 학습 및 가중치 확인
model.fit(train_x,train_y,epochs = 20)  #epoch수를 조정

# 은닉층은 튜닝해야합니다. 사격에서 영점 맞추는 것처럼
# epoch가 많으면 좋지만 과적합이 됩니다.


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 3)                 12        
                                                                 
 dense_10 (Dense)            (None, 6)                 24        
                                                                 
 dense_11 (Dense)            (None, 2)                 14        
                                                                 
Total params: 50 (200.00 Byte)
Trainable params: 50 (200.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
50/50 [==============================] - 1s 2ms/step - loss: 0.6512 - acc: 0.8375
Epoch 2/20
50/50 [==============================] - 0s 2ms/step - loss: 0.5646 - acc: 0.8550
Epoch 3/20
50/50 [==============================] - 0s 2ms/step - loss: 0.4648 - acc: 0.8550
Epo

5. 결과확인 및 평가

In [ ]:
#np.argmax
print( np.argmax( [1,10,100]) )

a = np.arange(6).reshape(2,3) + 10
print(a)
print(np.argmax(a, axis=0))#열에서 최대값, index
print(np.argmax(a, axis=1))#행에서 최대값, index 반환

2
[[10 11 12]
 [13 14 15]]
[1 1 1]
[2 2]


In [ ]:
predicted = model.predict( test_x)
predicted2 = np.argmax(predicted, axis=-1)
actual = np.argmax(test_y, axis=-1)

print("Accuracy:", np.mean(predicted2 == actual))


13/13 [==============================] - 0s 2ms/step
Accuracy: 0.95


In [ ]:
model.summary()
print( model.get_weights() ) #가중치 확인


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 3)                 12        
                                                                 
 dense_10 (Dense)            (None, 6)                 24        
                                                                 
 dense_11 (Dense)            (None, 2)                 14        
                                                                 
Total params: 50 (200.00 Byte)
Trainable params: 50 (200.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
[array([[ 1.0737674 ,  0.11256661,  1.1299431 ],
       [ 0.324261  , -1.0440769 , -0.39602026],
       [-0.6801691 ,  1.1892935 ,  0.23534544]], dtype=float32), array([0.19603086, 0.2529988 , 0.28356522], dtype=float32), array([[ 0.30980608, -0.4843143 ,  0.20941554,  1.2007492 , 

In [ ]:
#분류 보고서
from sklearn.metrics import classification_report, confusion_matrix
print('\n', classification_report(actual, predicted2))


               precision    recall  f1-score   support

           0       0.97      0.98      0.97       349
           1       0.83      0.76      0.80        51

    accuracy                           0.95       400
   macro avg       0.90      0.87      0.88       400
weighted avg       0.95      0.95      0.95       400

